// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("Personal Trainer")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2015, 2106 Figroll")]
[assembly: AssemblyVersionAttribute("0.9.0")]
[assembly: AssemblyFileVersionAttribute("0.9.0")]
[assembly: AssemblyTrademarkAttribute("f7643a5b8d31b46cf667ab76615aae3dada2d269")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.9.0";
    }
}
